import mysql.connector
import psycopg2
from dotenv import load_dotenv
import os
import regex as re
load_dotenv()

mysql_username = os.getenv("MYSQL_USERNAME")
mysql_password = os.getenv("MYSQL_PASSWORD")
pg_username = os.getenv("PG_USERNAME")
pg_password = os.getenv("PG_PASSWORD")
db_name = os.getenv("DB_NAME")


def connect_mysql(username, password, db_name):
    mysql_conn = mysql.connector.connect(
        host="localhost",
        user=username,
        password=password,
        database=db_name
    )
    return mysql_conn, mysql_conn.cursor(dictionary=True)

def connect_postgres(username, password, db_name):
    pg_conn = psycopg2.connect(
        host="localhost",
        user=username,
        password=password,
        database=db_name
    )
    return pg_conn, pg_conn.cursor()

def get_mysql_tables(cursor):
    cursor.execute("SHOW TABLES")
    tables = [list(row.values())[0] for row in cursor.fetchall()]
    return tables

def get_mysql_schema(cursor, table):
    cursor.execute(f"SHOW CREATE TABLE {table}")
    return cursor.fetchall()

TYPE_MAPPING = {
    "int": "INTEGER",
    "bigint": "BIGINT",
    "varchar": "VARCHAR",
    "text": "TEXT",
    "datetime": "TIMESTAMP",
    "float": "FLOAT"
}

def convert_datatype(mysql_type):
    mysql_type = mysql_type.lower()
    for key in TYPE_MAPPING:
        if key in mysql_type:
            return TYPE_MAPPING[key]
    return "TEXT"


def create_pg_table(table, schema, pg_conn, pg_cursor):
    columns = []

    for col in schema:
        col_name = col["Field"]
        col_type = convert_datatype(col["Type"])
        extra = col["Extra"]
        nullable = "" if col["Null"] == "Yes" else "Not Null"

        if 'auto_increment' in extra:
            column_def = f"{col_name} {col_type} GENERATED BY DEFAULT AS IDENTITY"
        else:
            nullable = "" if nullable else "NOT NULL"
            column_def = f"{col_name} {col_type} {nullable}".strip()
            
        columns.append(column_def)
        if 'auto_increment' in extra:
            columns.append(f"PRIMARY KEY ({col_name})")

    # create_sql = f"""
    #     CREATE TABLE IF NOT EXISTS {table} (
    #         {", ".join(columns)}
    #     );"""

    # pg_cursor.execute(create_sql)
    # pg_conn.commit()
    return columns


def migrate_data():
    pass



mysql_conn, mysql_cursor = connect_mysql(username=mysql_username, password=mysql_password, db_name=db_name)
pg_conn, pg_cursor = connect_postgres(username=pg_username, password=pg_password, db_name=db_name)

tables = get_mysql_tables(mysql_cursor)
# print(tables)

table_schema = []

for table in tables:
    schema = get_mysql_schema(mysql_cursor, table)
    table_schema.append(schema[0]["Create Table"])

    # a = create_pg_table(table, schema, pg_conn, pg_cursor)
    # print(a)

for i in table_schema:
    a = re.split(r"\sENGINE.*", i)
    print(a[0].replace("`", ''))
    print('\n')

mysql_cursor.close()
mysql_conn.close()